vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    user_avatar:
      uri_prefix: /uploads
      upload_destination: "%upload_directory%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
